language: generic

matrix:
    include:
        - os: osx
          env:
            - VERSION=2.7.13
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.4.4
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.5.2
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.6.0
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=2.7
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.4
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.5
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3.6
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=2
              SOURCE=homebrew
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=3
              SOURCE=homebrew
              DEPENDENCIES=pip
        - os: osx
          env:
            - VERSION=2.7
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          env:
            - VERSION=3.4
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          env:
            - VERSION=3.5
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          env:
            - VERSION=3.6
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          env:
            - VERSION=2
              SOURCE=homebrew
              DEPENDENCIES=homebrew
        - os: osx
          env:
            - VERSION=3
              SOURCE=homebrew
              DEPENDENCIES=homebrew

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  timeout: 500
  directories:
    - $HOME/Library/Caches/pip/wheel
    - $HOME/.pip-accel
    - $HOME/macports_cache
#    - /opt/local/var/macports/distfiles
#    - /opt/local/var/macports/incoming
    - $HOME/Library/Caches/Homebrew

env:
  global:
    - PYI_COMMIT=osx-caching
    - REPO_DIR=pyinstaller
    # shorten logging of pip-accel
    - PIP_ACCEL_LOG_FORMAT="%(name)-18s %(levelname)s %(message)s"
#    - PIP_ACCEL_LOG_VERBOSITY="debug"


# Install dependencies.
install:
  # Build Python interpreter
  - source terryfy/travis_tools.sh
  - source $TRAVIS_BUILD_DIR/utils.sh
  - get_python_environment $SOURCE $VERSION venv
  - register_cache
  - if [ $SOURCE = macports ]; then sudo port -pb install curl | cat; fi
  - source terryfy/test_python_installs.sh
  - if [ $SOURCE = macports ]; then export PYTHON_VERSION=`get_py_mm_nodot`; else export PYTHON_VERSION=`get_py_digit`; fi

  # Checkout latest PyInstaller.
  - cd $TRAVIS_BUILD_DIR
  - checkout_commit $REPO_DIR $PYI_COMMIT | cat

  # Compile bootloader.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR/bootloader
  - $PYTHON_EXE waf distclean all

  # Install PyInstaller.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
  - $PIP_CMD install -e .

  # Install dependencies for tests. Use pip-accel to cache compiled
  # packages and save recompiling each time.
  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  - ${PIP_CMD} install pip-accel
  - export ACCEL_CMD=`dirname $PIP_CMD`/pip-accel
  - ${ACCEL_CMD} install -r $TRAVIS_BUILD_DIR/$REPO_DIR/tests/requirements-tools.txt | cat
  - install_dependencies

script:
  # Make sure virtualenv is activated.
  - source $TRAVIS_BUILD_DIR/venv/bin/activate
  # Run tests and speed them up by sending them to multiple CPUs.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
#  - py.test -n 3
before_cache:
  - prep_cache
