language: cpp

matrix:
    include:
        - os: osx
          compiler: ": 2.7.11-macpython"
          env:
            - VERSION=2.7.11
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.3.5-macpython"
          env:
            - VERSION=3.3.5
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.4.4-macpython"
          env:
            - VERSION=3.4.4
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.5.1-macpython"
          env:
            - VERSION=3.5.1
              SOURCE=macpython
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 2.7-macports"
          env:
            - VERSION=2.7
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.3-macports"
          env:
            - VERSION=3.3
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.4-macports"
          env:
            - VERSION=3.4
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3.5-macports"
          env:
            - VERSION=3.5
              SOURCE=macports
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 2-homebrew"
          env:
            - VERSION=2
              SOURCE=homebrew
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 3-homebrew"
          env:
            - VERSION=3
              SOURCE=hombrew
              DEPENDENCIES=pip
        - os: osx
          compiler: ": 2.7-macports"
          env:
            - VERSION=2.7
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          compiler: ": 3.3-macports"
          env:
            - VERSION=3.3
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          compiler: ": 3.4-macports"
          env:
            - VERSION=3.4
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          compiler: ": 3.5-macports"
          env:
            - VERSION=3.5
              SOURCE=macports
              DEPENDENCIES=macports
        - os: osx
          compiler: ": 2-homebrew"
          env:
            - VERSION=2
              SOURCE=homebrew
              DEPENDENCIES=homebrew
        - os: osx
          compiler: ": 3-homebrew"
          env:
            - VERSION=3
              SOURCE=homebrew
              DEPENDENCIES=homebrew

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/Library/Caches/pip
    - $HOME/.pip-accel
    - $HOME/macports_cache
    - /Library/Caches/Homebrew

env:
  global:
    - PYI_COMMIT=develop
    - REPO_DIR=pyinstaller
    # shorten logging of pip-accel
    - PIP_ACCEL_LOG_FORMAT="%(name)-18s %(levelname)s %(message)s"
#    - PIP_ACCEL_LOG_VERBOSITY="debug"


# Install dependencies.
install:
  # Build Python interpreter
  - source terryfy/travis_tools.sh
  - get_python_environment $SOURCE $VERSION venv
  - if [ $SOURCE = macports ]; then sudo port -p install curl; fi
  - source terryfy/test_python_installs.sh
  - if [ $SOURCE = macports ]; then export PYTHON_VERSION=`get_py_mm_nodot`; else export PYTHON_VERSION=`get_py_digit`; fi

  # Checkout latest PyInstaller.
  - cd $TRAVIS_BUILD_DIR
  - checkout_commit $REPO_DIR $PYI_COMMIT

  # Compile bootloader.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR/bootloader
  - $PYTHON_EXE waf distclean all

  # Install PyInstaller.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
  - $PIP_CMD install -e .

  # Install dependencies for tests. Use pip-accel to cache compiled
  # packages and save recompiling each time.
  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  - ${PIP_CMD} install pip-accel
  - export ACCEL_CMD=`dirname $PIP_CMD`/pip-accel
  - ${ACCEL_CMD} install -r $TRAVIS_BUILD_DIR/$REPO_DIR/tests/requirements-tools.txt | cat
  - source $TRAVIS_BUILD_DIR/utils.sh
  - install_dependencies

script:
  # Make sure virtualenv is activated.
  - source $TRAVIS_BUILD_DIR/venv/bin/activate
  # Run tests and speed them up by sending them to multiple CPUs.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
  - py.test -n 5
