# Travis does not support Python on OS X directly yet so only set os not language.
os:
  - osx

# Cache pip packages. Explicitly name the pip-cache directory since we
# use a custom `install` step which annuls `cache: pip`.
cache:
  directories:
    - $HOME/Library/Caches/pip

env:
  global:
    - PYI_COMMIT=develop
    - REPO_DIR=pyinstaller
  matrix:
    - VERSION=2.7.13
      SOURCE=macpython
      DEPENDENCIES=pip
    - VERSION=3.4.4
      SOURCE=macpython
      DEPENDENCIES=pip
    - VERSION=3.5.3
      SOURCE=macpython
      DEPENDENCIES=pip
    - VERSION=3.6.1
      SOURCE=macpython
      DEPENDENCIES=pip
    - VERSION=2.7
      SOURCE=macports
      DEPENDENCIES=pip
    - VERSION=3.4
      SOURCE=macports
      DEPENDENCIES=pip
    - VERSION=3.5
      SOURCE=macports
      DEPENDENCIES=pip
    - VERSION=3.6
      SOURCE=macports
      DEPENDENCIES=pip
    - VERSION=2
      SOURCE=homebrew
      DEPENDENCIES=pip
    - VERSION=3
      SOURCE=homebrew
      DEPENDENCIES=pip
    - VERSION=2.7
      SOURCE=macports
      DEPENDENCIES=macports
    - VERSION=3.4
      SOURCE=macports
      DEPENDENCIES=macports
    - VERSION=3.5
      SOURCE=macports
      DEPENDENCIES=macports
    - VERSION=3.6
      SOURCE=macports
      DEPENDENCIES=macports
    - VERSION=2
      SOURCE=homebrew
      DEPENDENCIES=homebrew
    - VERSION=3
      SOURCE=homebrew
      DEPENDENCIES=homebrew


# Install dependencies.
install:
  # Build Python interpreter
  - cd terryfy; git submodule update --remote multibuild/; cd ..
  - source terryfy/travis_tools.sh
  - if [ $SOURCE != homebrew ]; then get_python_environment $SOURCE $VERSION venv; else get_python_environment $SOURCE $VERSION; fi
  - if [ $SOURCE = macports ]; then sudo port -p install curl; fi
  - source terryfy/test_python_installs.sh
  - if [ $SOURCE = macports ]; then export PYTHON_VERSION=`get_py_mm_nodot`; else export PYTHON_VERSION=`get_py_digit`; fi

  # Checkout latest PyInstaller.
  - cd $TRAVIS_BUILD_DIR
  - checkout_commit $REPO_DIR $PYI_COMMIT

  # Compile bootloader.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR/bootloader
  - $PYTHON_EXE waf distclean all

  # Install PyInstaller.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
  - $PIP_CMD install -e .

  # Install dependencies for tests.
  # Download-progress bars break Travis's log view. Disable them by piping output
  # through another program (if output is not a tty, no progress bars)
  - ${PIP_CMD} install -U pip
  - ${PIP_CMD} install -r $TRAVIS_BUILD_DIR/$REPO_DIR/tests/requirements-tools.txt | cat
  - source $TRAVIS_BUILD_DIR/utils.sh
  - install_dependencies

script:
  # Make sure virtualenv is activated.
  - source $TRAVIS_BUILD_DIR/venv/bin/activate
  # Run tests and speed them up by sending them to multiple CPUs.
  - cd $TRAVIS_BUILD_DIR/$REPO_DIR
#  - py.test -n 5
